#!/usr/bin/env Rscript
# setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(dplyr)
library(tidyr)
library(purrr)
library(MASS)
library(mvtnorm)
library(lpSolve)
library(glmnet)
source("kernel/DGM.R", chdir = TRUE)
source("kernel/estimation.R", chdir = TRUE)
source("kernel/utils.R", chdir = TRUE)
source("kernel/trial.R", chdir = TRUE)

trial(res_dir = "/homes/dag89/hdiv/res2/")
